Parsing of multiple with statments added
reata/sqllineage pull request #114
Opened 2021-01-21 19:40 UTC by Vendetta01

The following SQL statement results in an Exception:
```sql
WITH wtab1 AS (SELECT * FROM tab1),
wtab2 AS (SELECT * FROM tab2)
SELECT *
FROM wtab1
```

The reason is that after a with statement an _Identifier_ is assumed. The above example however results in an _IdentifierList_. This pull request addresses this issue by extending *_handle_temp_table_token* to also check for *IdentifierList* and resolving that case as needed.
I also added two new tests.

Last but not least let me thank you for your great work on this project!

2021-01-23 02:36 UTC, reata requested changes
Thanks for your PR. Personally I rarely use CTE, and it's good to get cases like this covered.

The overall implementation looks good to me, except for some coding style issues. I made some comments, please change the code accordingly. 

And please fix all the broken GitHub Actions checks before next review. I know these're hidden rules running background that may seem unclear to you. I'll add a contributing guide to this repo later. Before that, just check GitHub Actions, see the log and follow what it says. Sorry for the inconvenience.

2021-01-23 02:36 UTC, reata commented on tests/test_select.py
> +    )
1. Change the testing SQL to the following. With column name specified, I believe it makes more sense for multiple CTE subclauses. FYI, I get this SQL from MySQL manual (https://dev.mysql.com/doc/refman/8.0/en/with.html). 
```sql
WITH
  cte1 AS (SELECT a, b FROM table1),
  cte2 AS (SELECT c, d FROM table2)
SELECT b, d FROM cte1 JOIN cte2
WHERE cte1.a = cte2.c;
```

2. Add a new line at end of file. It's always good coding style to end a file with newline.

2021-01-23 02:36 UTC, reata commented on sqllineage/core.py
> +                Table.create(sub_token))
I'm trying to enforce black code style. So according to black check, make this one line. 

You can see the black check result in GitHub actions (https://github.com/reata/sqllineage/pull/114/checks?check_run_id=1744343710) for this PR.
Or better, you can try adding [pre-commit](https://pre-commit.com/) hoot for your local git repo so each time before git commit, some sort of checks will be enforced before pushing to GitHub. I have a [pre-commit configuration file](https://github.com/reata/sqllineage/blob/master/.pre-commit-config.yaml) in the repo.

2021-01-23 02:36 UTC, reata commented on sqllineage/core.py
> +                        Table.create(temp_tab_token))
Same as above, make it one line.

2021-01-23 02:36 UTC, reata commented on sqllineage/core.py
> +                "An Identifier(List) is expected, got %s[value: %s] instead"
We might as well make it explicit here. After all, [Explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/).

"An Identifier or IdentifierList is expected, got %s[value: %s] instead"

2021-01-23 19:26 UTC, Vendetta01 commented
Thank you for your detailed feedback, I incorporated all requested changes into the branch.

2021-01-24 13:46 UTC, reata approved these changes
LGTM

2021-01-24 13:48 UTC, merged