add check union directly in sqllineage/core/parser/sqlfluff/utils.py
reata/sqllineage pull request #391
Opened 2023-06-15 06:43 UTC by duongphannamhung

add check union direct inside cte, we current just have check union in raw segment

2023-06-15 13:24 UTC, reata commented
Would you fix the CI? You can run it in your local env via `tox -e py38`. Or change to your local Python version like py39 or py310. You can rely on GitHub Actions for multiple Python version test though if you don't have to set it up locally.

2023-06-15 13:55 UTC, duongphannamhung commented
I just fix the CI, thank you

2023-06-16 11:53 UTC, reata requested changes
Please address my comment inline. Also let me know if you're interested in making it work with sqlparse as well.

2023-06-16 11:53 UTC, reata commented on tests/test_others_dialect_specific.py
This is duplicated test case. Let's remove it and keep it only in test_columns.py

2023-06-16 11:53 UTC, reata commented on sqllineage/core/parser/sqlfluff/extractors/cte_extractor.py
> +
I think we can move this part under `if sub_segment.type == "bracketed":`

2023-06-16 11:53 UTC, reata commented on sqllineage/core/parser/sqlfluff/utils.py
> +
Any particular reason we had to add this. The test case would also pass using `is_union`

2023-06-17 15:12 UTC, duongphannamhung commented
Really appreciate your comments, to be `is_isomorphic` like sqlparse makes me rethink the way my commit work so I have a little few changes, hope it's working out

2023-06-19 14:07 UTC, merged