Handle optional parent for col lineage
reata/sqllineage pull request #397
Opened 2023-06-21 12:33 UTC by ulixius9

Handle where parent is not available, also add support for `create_table_as_statement` which is specific to postgres dialect for sqlfluff

2023-06-24 14:45 UTC, reata reviewed
Can we add some test cases? I don't understand what are we supporting with this PR.

2023-06-29 13:38 UTC, reata commented
Is there any test case for column parent being optional?

2023-06-29 20:43 UTC, biswasarijit84 approved these changes

2023-07-02 06:46 UTC, reata requested changes
Let's make the test case more explanatory. The code logic change looks good to me.

2023-07-02 06:46 UTC, reata commented on tests/test_sqlfluff.py
Since this PR fixes two use cases, we'd better split the test cases into two parts so each is as atomic as possible:

1. sqlfluff uses create_table_as_statement regarding postgres dialect, create table as + postgres is the key. CTE is not related.
2. source column parent being optional, this is specific with the subquery part of following sql, which should be a separate test case.:
```sql
SELECT (select column1 + column2 as result) as sum_result
FROM my_table
```

2023-07-02 07:07 UTC, reata commented on tests/test_sqlfluff.py
For test case 1, it's not limited to postgres. sqlfluff has a set of dialects with parser deriving from postgres: duckdb, greenplum, materialize, redshift. We should list all of them in test case.

2023-07-02 07:48 UTC, merged