Set param from config
reata/sqllineage pull request #545
Opened 2024-01-10 12:53 UTC by delphisharp

Dear ALL：

https://github.com/reata/sqllineage/discussions/544

The default schema name is now implemented through environment variables. 
Now I have another way to implement it. Hope to discuss with everyone.

2024-01-10 13:31 UTC, maoxingda commented on sqllineage/config.py
> +    def __init__(self):
mypy不允许方法定义不加 **annotation**

2024-01-10 14:36 UTC, delphisharp commented on sqllineage/config.py
> +    def __init__(self):
yes . you are  right
see https://mypy.readthedocs.io/en/stable/common_issues.html

change to 
```python
def __init__(self) -> None
``` 
is OK

2024-01-11 04:53 UTC, delphisharp commented
已重新提交代码。 本地测试通过。 
Code has been resubmitted. The local pytest passed.

2024-01-14 11:13 UTC, delphisharp commented
Due to code format reasons, resubmit.

2024-01-14 11:33 UTC, maoxingda commented
https://github.com/maoxingda/sqllineage/blob/0823bf2e32f19d0f64a2c7acb951213db8696b93/sqllineage/config.py#L19

我感觉你这个改动有点问题呀，你现在的写法不支持环境变量的配置了。

I feel there is something wrong with your change. Your current writing method does not support the configuration of environment variables.

https://github.com/reata/sqllineage/pull/540

我正在通过环境变量的方式配置是否启用 **列别名引用功能**

I am configuring whether to enable the **lateral column alias reference function** through environment variables.

2024-01-14 11:36 UTC, reata requested changes
Please address the comment inline. Also check the uncovered lines and add unit test for it.

2024-01-14 11:36 UTC, reata commented on sqllineage/config.py
> +    TSQL_NO_SEMICOLON: SQLLineageConfigValue
Make these two dataclass private as well. Only expose instance SQLLineageConfig from this module.

2024-01-14 11:36 UTC, reata commented on sqllineage/config.py
> +        )
DO NOT make breaking change. Still try read from environment variable first, if not found then fallback to default value.

2024-01-14 11:36 UTC, reata commented on sqllineage/core/models.py
> +schema_unknown = "<default>"
Any particular reason that you'd like to move this variable out of Schema?

2024-01-14 11:36 UTC, reata commented on sqllineage/runner.py
> +        tsql_no_semicolon: Optional[bool] = False,
I'd prefer explicitly ask user to set value on SQLLineageConfig, and not through LineageRunner interface.

2024-01-14 11:40 UTC, reata commented
> https://github.com/maoxingda/sqllineage/blob/0823bf2e32f19d0f64a2c7acb951213db8696b93/sqllineage/config.py#L19
> 
> 我感觉你这个改动有点问题呀，你现在的写法不支持环境变量的配置了。
> 
> I feel there is something wrong with your change. Your current writing method does not support the configuration of environment variables.
> 
> #540
> 
> 我正在通过环境变量的方式配置是否启用 **列别名引用功能**
> 
> I am configuring whether to enable the **lateral column alias reference function** through environment variables.

Agreed, we need to maintain support config through environment variables. This approach is read only.

The new ability we're adding through this PR is to set config at run time via Python code.

2024-01-14 12:53 UTC, delphisharp commented
刚才在添加测试用例，各位意见现在看到了。我总结下：
1.  优先走环境变量
2. 单独从配置类中读取
3. 参数不通过Runner传递，通过设定 config类实现


I was adding test cases just now, and your comments are now visible. Let me summarize:
1. Prioritize environment variables
2. Read from the configuration from config Class 
3.  he parameters are not passed through the Runner，  set config class

2024-01-14 17:18 UTC, delphisharp commented
use black,  
```python
item[self._len_prefix : len(self._PREFIX)] 
```
must be have whitespace.

but use flask8,
./sqllineage/config.py:38:47: E203 whitespace before ':'
            self._config[item[self._len_prefix : len(self._PREFIX)]][


how to do?

2024-01-15 03:15 UTC, closed without merging