fix: Set param from config #545
reata/sqllineage pull request #553
Opened 2024-01-15 03:19 UTC by delphisharp

Dear ALL：

目前模型的默认模式名是通过环境变量传递的，我认为实现方法不够python。
所以，我实现了另一种解决方法。

修改 sqllineage/config.py 实现配置项的读取和写入， 读取方法保持和已有方法兼容。
修改 sqllineage/core/models.py 的Schema 类，在每次初始化的时候动态读取配置
修改 sqllineage/runner.py的init方法，传入变量，并在 SQLLineageConfig 赋值
请大家提出意见，谢谢
Currently the default schema name of the model is passed through environment variables, and I think the implementation method is not python enough.
So, I implemented another workaround.

Modify sqllineage/config.py to implement reading and writing of configuration items. The reading method remains compatible with the existing method.
Modify the Schema class of sqllineage/core/models.py and dynamically read the configuration every time it is initialized.
Modify the init method of sqllineage/runner.py, pass in variables, and assign values in SQLLineageConfig
Please give your opinions, thank you

重新建立分支并提交
Re-branch and submit

2024-01-15 15:05 UTC, reata commented
Do we have all the codes in this new branch? I remember we need to change the Schema model in #545

2024-01-16 03:08 UTC, delphisharp commented
> Do we have all the codes in this new branch? I remember we need to change the Schema model in #545

Sorry, there were some problems when my local branch was synchronized from upstream changes of the master. 
So a new branch was reopened.

2024-01-16 14:04 UTC, reata commented
What's the difference between this and #555 ? Do they jointly solve #536 and is there any dependency, like I need to merge this PR first and then #555?

2024-01-18 15:27 UTC, reata requested changes
Change config at runtime is a dangerous thing as we discussed previously under multi-thread context. Although we normally encourage user to use multi-process for bulk process, but thread-safety is still something we need to guarantee given SQLLineageConfig is a global variable. 

With that in mind, I'd like to propose this API leveraging Python context manager:

```python
with SQLLineageConfig.set(DEFAULT_SCHEMA="ods", TSQL_NO_SEMICOLON=True):
    runner = LineageRunner(sql)
    print(runner.source_tables)
```
Once entering the with block, those config are temporarily set to another value for current thread and are only readable to current thread. And the temporary value is cleaned up after exit with block.

At the heart of the implementation, we should have a data structure like:
```
{
    "thread_1": {"DEFAULT_SCHEMA": "ods", "TSQL_NO_SEMICOLON": True},
    "thread_2": {"DEFAULT_SCHEMA": "default"}
}
```
which takes highest priority > environment variable > default value

2024-01-18 15:27 UTC, reata commented on sqllineage/config.py
> +        }
Let's not change the config data structure. Just create a separate variable to store the value set at runtime.

2024-03-10 14:52 UTC, reata requested changes
Please stick to our design that user need to explicitly call set method instead of \_\_setattr\_\_:

```python
with SQLLineageConfig.set(DEFAULT_SCHEMA="ods", TSQL_NO_SEMICOLON=True):
    runner = LineageRunner(sql)
    print(runner.source_tables)
```

2024-04-07 08:11 UTC, reata approved these changes
LGTM

2024-04-07 08:13 UTC, merged